name: Go

on:
  push:
    branches: [ $default-branch, "develop" ]
  pull_request:
    branches: [ $default-branch, "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Set dependencies
        run: sudo apt update && sudo apt install musl-tools
      - name: Generate SSH key
        run: ssh-keygen -f ~/.ssh/id_rsa -P=""
      - name: Build
        run: make build
      - name: Test
        run: make test
